import type { Phase1Question, Phase2Question, ChapterKey, ChapterDef, MascotType } from './types'

export const chapters: Record<ChapterKey, ChapterDef & { mascot: MascotType }> = {
  profilo: { mascot: 'commute', title: 'Area e ruolo', desc: 'Qualche informazione di contesto su di te.' },
  relazioni: { mascot: 'talk', title: 'Le tue relazioni sul lavoro', desc: 'Colleghi, referente diretto, HR e management.' },
  crescita: { mascot: 'growth', title: 'Autonomia e crescita', desc: 'Come lavori ogni giorno e dove ti porta il tuo percorso.' },
  valori: { mascot: 'tech', title: 'Tecnologia e Valori', desc: "Qual è la tua percezione del ruolo di OT in questi ambiti?" },
  energia2: { mascot: 'flow', title: 'Carico ed energia', desc: 'Sostenibilità del lavoro e possibilità di recupero.' },
  riflessione: { mascot: 'timeline', title: 'Prospettive', desc: 'Desideriamo conoscere ancora qualcos\'altro…' },
  chiusura: { mascot: 'finish', title: 'Ultimo step', desc: 'Manca pochissimo per completare il test!' },
}

type Step2Item = Phase2Question & { chapter: ChapterKey | null }

export const step2: Step2Item[] = [
  {
    id: 'bu',
    chapter: 'profilo',
    type: 'single',
    title: 'La tua area di appartenenza',
    sub: 'BU / CDC principale',
    options: [
      'Operation & Delivery (tutti i team di lavoro, SYS, APA, ...)',
      'Sales & Marketing',
      'IT (interno, helpdesk...)',
      'HR (HR payroll; Recruiting & Development; Language Specialist)',
      'Servizi generali (Amministrazione, Office Coordinator)',
    ],
  },
  {
    id: 'anzianita',
    chapter: null,
    type: 'single',
    title: 'Da quanto tempo sei in azienda?',
    options: ['< 1 anno', '1-2 anni', '3-4 anni', '5-6 anni', '7-8-9 anni', '>= 10 anni'],
  },
  {
    id: 'ruolo',
    chapter: null,
    type: 'single',
    title: 'Il tuo ruolo',
    options: ['Manager', 'Worker'],
  },
  { id: 'relazioni_q', chapter: 'relazioni', type: 'likert5', group: '🤝 I colleghi', title: 'Le relazioni interpersonali nel mio ambiente di lavoro sono costruttive' },
  { id: 'referente_crescita', chapter: null, type: 'likert5', group: '👤 Responsabile', title: 'Il/la mio/a diretto referente mi supporta nella mia crescita professionale' },
  { id: 'referente_obiettivi', chapter: null, type: 'likert5', group: '👤 Responsabile', title: 'Il/la mio/a diretto referente dà obiettivi strutturati' },
  { id: 'hr_access', chapter: null, type: 'likert5', group: '🏥 HR', title: "L'HR è un punto di riferimento accessibile e disponibile quando ne ho bisogno" },
  { id: 'hr_valore', chapter: null, type: 'likert5', group: '🏥 HR', title: "Riconosco un valore reale nel supporto che l'HR mi offre" },
  { id: 'mgmt_trasp', chapter: null, type: 'likert5', group: '🏢 Management', title: 'Il management aziendale comunica in modo trasparente la strategia e le priorità' },
  { id: 'mgmt_fiducia', chapter: null, type: 'likert5', group: '🏢 Management', title: 'Ho fiducia nelle scelte strategiche del management' },
  { id: 'jc_task', chapter: 'crescita', type: 'likert5', group: '⚙️ Autonomia nel lavoro', title: 'Ho la possibilità di proporre nuove modalità per svolgere i miei compiti' },
  { id: 'jc_schemi', chapter: null, type: 'likert5', group: '⚙️ Autonomia nel lavoro', title: 'Mi sento libero/a di sperimentare soluzioni diverse da quelle standard nel mio lavoro' },
  {
    id: 'sv_crescita',
    chapter: null,
    type: 'multi',
    group: '🌱 Crescita professionale',
    max: 2,
    title: 'A cosa attribuisci principalmente la tua crescita professionale in OT?',
    sub: 'Scegli fino a 2 opzioni',
    options: [
      'Le opportunità offerte dall\'azienda (formazione, progetti, ruoli)',
      'Il supporto del mio responsabile diretto',
      'Il confronto con i colleghi',
      'La mia iniziativa personale',
      'Percorsi di formazione esterni',
      'Non sento di stare crescendo professionalmente',
    ],
  },
  { id: 'engagement', chapter: 'valori', type: 'likert5', group: '💡 Valori aziendali', title: 'Mi identifico nei valori e nel modo di lavorare di OT' },
  { id: 'tecnologia', chapter: null, type: 'likert5', group: '💻 Tecnologia', title: "OT investe in modo adeguato nell'innovazione tecnologica" },
  { id: 'stress_carico', chapter: 'energia2', type: 'likert5', group: '🔋 Carico di lavoro', title: 'Il carico di lavoro che gestisco quotidianamente è sostenibile' },
  { id: 'stress_recupero', chapter: null, type: 'likert5', group: '😴 Recupero', title: 'Riesco a staccare dal lavoro e recuperare le energie nel tempo libero' },
  {
    id: 'priorita',
    chapter: 'riflessione',
    type: 'multi',
    group: '🎯 Cosa vorresti migliorare',
    max: 3,
    title: 'Cosa vorresti cambiare per incrementare la tua soddisfazione lavorativa?',
    sub: 'Scegli fino a 3 opzioni',
    options: [
      'Costruire ottime relazioni con i colleghi in un ambiente più accogliente',
      'Avere obiettivi SMART stabiliti con il/la responsabile',
      'Avere un ottimo rapporto con il mio responsabile',
      'Ottenere feedback da responsabili e/o colleghi per migliorare',
      'Avere formazione ad hoc per il mio percorso',
      'Avere una crescita professionale',
      'Avere maggiore inclusione e rispetto delle mie unicità',
      'Altro',
    ],
    hasInputOn: 'Altro',
  },
  {
    id: 'open_listening',
    chapter: null,
    type: 'likert5',
    group: '📢 Open Listening 2025',
    optional: true,
    alert: 'Rispondi solo se hai partecipato alla sessione di Open Listening 2025',
    scaleLabels: ['Molto insoddisfacente', 'Molto soddisfacente'],
    title: "Rispetto all'ultimo Open Listening, sono state messe in atto azioni concrete?",
    sub: '',
  },
  { id: 'soddisfazione', chapter: 'chiusura', type: 'likert5', group: '❤️ Passione', title: 'Il lavoro che svolgo ogni giorno mi appassiona' },
  {
    id: 'nps',
    chapter: null,
    type: 'nps',
    group: '⭐ Raccomandazione',
    title: 'Quanto raccomanderesti OT come un buon posto di lavoro?',
    sub: 'A un amico, familiare o ex collega — da 0 a 10',
  },
]

export const step1: Phase1Question[] = [
  {
    id: 'clima',
    type: 'single-icon',
    title: 'Che tempo fa nel tuo team?',
    sub: '',
    options: [
      { icon: '☀️', label: 'Soleggiato', desc: 'Clima collaborativo, caldo e stimolante' },
      { icon: '⛅', label: 'Parzialmente nuvoloso', desc: 'Tutto sommato stabile, con qualche area di miglioramento' },
      { icon: '🌧️', label: 'Piovoso', desc: "Sotto pressione, stanco, qualche frizione nell'area" },
      { icon: '⛈️', label: 'Temporalesco', desc: 'Forte sovraccarico, stress o conflitti da risolvere' },
    ],
  },
  {
    id: 'termometro',
    type: 'slider',
    title: 'Il termometro della tua energia',
    sub: 'Quanto ti senti carico o scarico in questo periodo?',
    messages: {
      1: ['😴', 'Energia al minimo: ogni ricarica parte da qui. Prenderne atto è il primo passo per recuperare forze.'],
      2: ['🪫', 'Carica bassa: la determinazione non manca. Un passo alla volta e ritroverai la carica.'],
      3: ['😕', 'Rallentamento ricco di potenziale: capire cosa ti stanca ti aiuterà a ripartire.'],
      4: ['🥱', 'Stanchezza accumulata: con i giusti ritmi tornerai presto al top.'],
      5: ['😐', 'Equilibrio e ricarica: una base solida da cui ripartire con energia.'],
      6: ['🙂', 'Stabilità in corso: avanti così con costanza!'],
      7: ['💪', 'Ottima carica: affronti le giornate con determinazione e focus.'],
      8: ['🚀', 'Carico/a e motivato/a: la tua energia fa la differenza per il team.'],
      9: ['🌟', 'Energia e entusiasmo: un riferimento contagioso e propositivo.'],
      10: ['🔥', 'Al massimo della carica: pronto/a a conquistare ogni traguardo!'],
    },
  },
  {
    id: 'causa',
    type: 'multi-icon',
    max: 2,
    title: 'Cosa influenza di più la tua energia ora?',
    sub: 'Scegli fino a 2 opzioni',
    options: [
      { icon: '🔋', label: 'Carico di lavoro' },
      { icon: '🤝', label: 'Relazioni con colleghi' },
      { icon: '🎯', label: 'Rapporto con il/la responsabile' },
      { icon: '🌱', label: 'Crescita e sviluppo professionale' },
      { icon: '🏠', label: 'Motivi personali/extra-lavorativi' },
      { icon: '🛠️', label: 'Strumenti e organizzazione' },
      { icon: '✏️', label: 'Altro', hasInput: true },
    ],
  },
  {
    id: 'descrizione',
    type: 'single-icon',
    title: "Come descriveresti la tua energia quest'anno?",
    sub: '',
    options: [
      { icon: '⚡', label: 'Energia in Crescita', desc: 'Spinta & propulsione: alta motivazione, voglia di nuove sfide' },
      { icon: '🔋', label: 'Energia Stabile', desc: 'Equilibrio & regolarità: carica costante, ritmo sostenibile' },
      { icon: '🪫', label: 'Energia in Ricarica', desc: 'Bisogno di nuova linfa: carica in calo, serve ricaricare' },
      { icon: '🌱', label: 'Energia in Assestamento', desc: 'Ti stai riorganizzando su nuovi ritmi e priorità' },
    ],
  },
]
